package ints

import (
	"cmp"
	"fmt"
)

// Int32 is a type that represents an 32-bit signed integer.
// It is an alias for the built-in int32 type.
type Int32 int32

// IsZero returns true if a is zero.
func (a Int32) IsZero() bool {
	return a == 0
}

// Add returns the sum a+b.
//
// This function's execution time does not depend on the inputs.
func (a Int32) Add(b Int32) Int32 {
	return a + b
}

// Sub returns the difference a-b.
//
// This function's execution time does not depend on the inputs.
func (a Int32) Sub(b Int32) Int32 {
	return a - b
}

// Mul returns the product a*b.
//
// This function's execution time does not depend on the inputs.
func (a Int32) Mul(b Int32) Int32 {
	return a * b
}

// Div returns the quotient a/b for b != 0.
// If b == 0, a division-by-zero run-time panic occurs.
// Div implements Euclidean division (unlike Go); see [Int32.DivMod] for more details.
func (a Int32) Div(b Int32) Int32 {
	q, _ := a.DivMod(b)
	return q
}

// Mod returns the remainder a%b for b != 0.
// If b == 0, a division-by-zero run-time panic occurs.
// Mod implements Euclidean division (unlike Go); see [Int32.DivMod] for more details.
func (a Int32) Mod(b Int32) Int32 {
	_, r := a.DivMod(b)
	return r
}

// DivMod returns the quotient and remainder of a/b.
// DivMod implements Euclidean division and modulus (unlike Go):
//
//	q = a div b  such that
//	m = a - b*q  with 0 <= m < |b|
//
// (See Raymond T. Boute, “The Euclidean definition of the functions
// div and mod”. ACM Transactions on Programming Languages and
// Systems (TOPLAS), 14(2):127-144, New York, NY, USA, 4/1992.
// ACM press.)
// See [Int32.QuoRem] for T-division and modulus (like Go).
func (a Int32) DivMod(b Int32) (Int32, Int32) {
	q, r := a/b, a%b
	if r < 0 {
		if b > 0 {
			r += b
			q--
		} else {
			r -= b
			q++
		}
	}
	return q, r
}

// Quo returns the quotient a/b for b != 0.
// If b == 0, a division-by-zero run-time panic occurs.
// Quo implements T-division (like Go); see [Int32.QuoRem] for more details.
func (a Int32) Quo(b Int32) Int32 {
	return a / b
}

// Rem returns the remainder a%b for b != 0.
// If b == 0, a division-by-zero run-time panic occurs.
// Rem implements T-division (like Go); see [Int32.QuoRem] for more details.
func (a Int32) Rem(b Int32) Int32 {
	return a % b
}

// QuoRem returns the quotient and remainder of a/b.
// QuoRem implements T-division and modulus (like Go):
//
//	q = a/b      with the result truncated to zero
//	r = a - b*q
//
// (See Daan Leijen, “Division and Modulus for Computer Scientists”.)
// See [Int32.DivMod] for Euclidean division and modulus (unlike Go).
func (a Int32) QuoRem(b Int32) (Int32, Int32) {
	return a / b, a % b
}

// Lsh returns the logical left shift a<<i.
//
// This function's execution time does not depend on the inputs.
func (a Int32) Lsh(i uint) Int32 {
	return a << i
}

// Rsh returns the arithmetic right shift a>>i, preserving the sign bit.
//
// This function's execution time does not depend on the inputs.
func (a Int32) Rsh(i uint) Int32 {
	return a >> i
}

// Sign returns the sign of a.
// It returns 1 if a > 0, -1 if a < 0, and 0 if a == 0.
func (a Int32) Sign() int {
	switch {
	case a > 0:
		return 1
	case a < 0:
		return -1
	default:
		return 0
	}
}

// Neg returns the negation of a.
//
// This function's execution time does not depend on the inputs.
func (a Int32) Neg() Int32 {
	return -a
}

// Cmp returns the comparison result of a and b.
// It returns -1 if a < b, 0 if a == b, and 1 if a > b.
func (a Int32) Cmp(b Int32) int {
	return cmp.Compare(a, b)
}

// Text returns the string representation of a in the given base.
// Base must be between 2 and 62, inclusive.
// The result uses the lower-case letters 'a' to 'z' for digit values 10 to 35,
// and the upper-case letters 'A' to 'Z' for digit values 36 to 61. No prefix (such as "0x") is added to the string.
func (a Int32) Text(base int) string {
	return formatInt(int64(a), base)
}

// Append appends the string representation of a, as generated by a.Text(base), to buf and returns the extended buffer.
func (a Int32) Append(dst []byte, base int) []byte {
	return appendInt(dst, int64(a), base)
}

// AppendText implements the [encoding.TextAppender] interface.
func (a Int32) AppendText(dst []byte) ([]byte, error) {
	return appendInt(dst, int64(a), 10), nil
}

// String returns the string representation of a in base 10.
func (a Int32) String() string {
	return formatInt(int64(a), 10)
}

// Format implements [fmt.Formatter].
func (a Int32) Format(s fmt.State, verb rune) {
	sign := a.Sign()
	b := Uint32(a)
	if sign < 0 {
		b = b.Neg()
	}
	format(s, verb, sign, b)
}
