package ints

import "cmp"

// Int64 is a type that represents an 64-bit signed integer.
// It is an alias for the built-in int64 type.
type Int64 int64

// Add returns the sum a+b.
//
// This function's execution time does not depend on the inputs.
func (a Int64) Add(b Int64) Int64 {
	return a + b
}

// Sub returns the difference a-b.
//
// This function's execution time does not depend on the inputs.
func (a Int64) Sub(b Int64) Int64 {
	return a - b
}

// Mul returns the product a*b.
//
// This function's execution time does not depend on the inputs.
func (a Int64) Mul(b Int64) Int64 {
	return a * b
}

// Lsh returns the logical left shift a<<i.
//
// This function's execution time does not depend on the inputs.
func (a Int64) Lsh(i uint) Int64 {
	return a << i
}

// Rsh returns the arithmetic right shift a>>i, preserving the sign bit.
//
// This function's execution time does not depend on the inputs.
func (a Int64) Rsh(i uint) Int64 {
	return a >> i
}

// Sign returns the sign of a.
// It returns 1 if a > 0, -1 if a < 0, and 0 if a == 0.
func (a Int64) Sign() int {
	switch {
	case a > 0:
		return 1
	case a < 0:
		return -1
	default:
		return 0
	}
}

// Neg returns the negation of a.
//
// This function's execution time does not depend on the inputs.
func (a Int64) Neg() Int64 {
	return -a
}

// Cmp returns the comparison result of a and b.
// It returns -1 if a < b, 0 if a == b, and 1 if a > b.
func (a Int64) Cmp(b Int64) int {
	return cmp.Compare(a, b)
}

// Text returns the string representation of a in the given base.
// Base must be between 2 and 62, inclusive.
// The result uses the lower-case letters 'a' to 'z' for digit values 10 to 35,
// and the upper-case letters 'A' to 'Z' for digit values 36 to 61. No prefix (such as "0x") is added to the string.
func (a Int64) Text(base int) string {
	return formatInt(int64(a), base)
}

// Append appends the string representation of a, as generated by a.Text(base), to buf and returns the extended buffer.
func (a Int64) Append(dst []byte, base int) []byte {
	return appendInt(dst, int64(a), base)
}

// AppendText implements the [encoding.TextAppender] interface.
func (a Int64) AppendText(dst []byte) ([]byte, error) {
	return appendInt(dst, int64(a), 10), nil
}

// String returns the string representation of a in base 10.
func (a Int64) String() string {
	return formatInt(int64(a), 10)
}
