package ints

// Int8 is a type that represents an 8-bit signed integer.
// It is an alias for the built-in int8 type.
type Int8 int8

// Add returns the sum a+b.
//
// This function's execution time does not depend on the inputs.
func (a Int8) Add(b Int8) Int8 {
	return a + b
}

// Sub returns the difference a-b.
//
// This function's execution time does not depend on the inputs.
func (a Int8) Sub(b Int8) Int8 {
	return a - b
}

// Sign returns the sign of a.
// It returns 1 if a > 0, -1 if a < 0, and 0 if a == 0.
func (a Int8) Sign() int {
	switch {
	case a > 0:
		return 1
	case a < 0:
		return -1
	default:
		return 0
	}
}

// Neg returns the negation of a.
//
// This function's execution time does not depend on the inputs.
func (a Int8) Neg() Int8 {
	return -a
}

// Text returns the string representation of a in the given base.
// Base must be between 2 and 62, inclusive.
// The result uses the lower-case letters 'a' to 'z' for digit values 10 to 35,
// and the upper-case letters 'A' to 'Z' for digit values 36 to 61. No prefix (such as "0x") is added to the string.
func (a Int8) Text(base int) string {
	return formatInt(int64(a), base)
}

// Append appends the string representation of a, as generated by a.Text(base), to buf and returns the extended buffer.
func (a Int8) Append(dst []byte, base int) []byte {
	return appendInt(dst, int64(a), base)
}

// AppendText implements the [encoding.TextAppender] interface.
func (a Int8) AppendText(dst []byte) ([]byte, error) {
	return appendInt(dst, int64(a), 10), nil
}

// String returns the string representation of a in base 10.
func (a Int8) String() string {
	return formatInt(int64(a), 10)
}
