package ints

// Uint8 is a type that represents an 8-bit unsigned integer.
// It is an alias for the built-in uint8 type.
type Uint8 uint8

// Add returns the sum a+b.
//
// This function's execution time does not depend on the inputs.
func (a Uint8) Add(b Uint8) Uint8 {
	return a + b
}

// Sub returns the difference a-b.
//
// This function's execution time does not depend on the inputs.
func (a Uint8) Sub(b Uint8) Uint8 {
	return a - b
}

// Mul returns the product a*b.
func (a Uint8) Mul(b Uint8) Uint8 {
	return a * b
}

// Text returns the string representation of a in the given base.
// Base must be between 2 and 62, inclusive.
// The result uses the lower-case letters 'a' to 'z' for digit values 10 to 35,
// and the upper-case letters 'A' to 'Z' for digit values 36 to 61. No prefix (such as "0x") is added to the string.
func (a Uint8) Text(base int) string {
	return formatUint(uint64(a), base)
}

// Append appends the string representation of a, as generated by a.Text(base), to buf and returns the extended buffer.
func (a Uint8) Append(dst []byte, base int) []byte {
	return appendUint(dst, uint64(a), base)
}

// AppendText implements the [encoding.TextAppender] interface.
func (a Uint8) AppendText(dst []byte) ([]byte, error) {
	return appendUint(dst, uint64(a), 10), nil
}

// String returns the string representation of a in base 10.
func (a Uint8) String() string {
	return formatUint(uint64(a), 10)
}
