package ints

// Uint32 is a type that represents an 32-bit unsigned integer.
// It is an alias for the built-in uint32 type.
type Uint32 uint32

// Add returns the sum a+b.
//
// This function's execution time does not depend on the inputs.
func (a Uint32) Add(b Uint32) Uint32 {
	return a + b
}

// Sub returns the difference a-b.
//
// This function's execution time does not depend on the inputs.
func (a Uint32) Sub(b Uint32) Uint32 {
	return a - b
}

// Neg returns the negation of a.
//
// This function's execution time does not depend on the inputs.
func (a Uint32) Neg() Uint32 {
	return -a
}

// Text returns the string representation of a in the given base.
// Base must be between 2 and 62, inclusive.
// The result uses the lower-case letters 'a' to 'z' for digit values 10 to 35,
// and the upper-case letters 'A' to 'Z' for digit values 36 to 61. No prefix (such as "0x") is added to the string.
func (a Uint32) Text(base int) string {
	return formatUint(uint64(a), base)
}

// Append appends the string representation of a, as generated by a.Text(base), to buf and returns the extended buffer.
func (a Uint32) Append(dst []byte, base int) []byte {
	return appendUint(dst, uint64(a), base)
}

// AppendText implements the [encoding.TextAppender] interface.
func (a Uint32) AppendText(dst []byte) ([]byte, error) {
	return appendUint(dst, uint64(a), 10), nil
}

// String returns the string representation of a in base 10.
func (a Uint32) String() string {
	return formatUint(uint64(a), 10)
}
