package ints

import "math/bits"

// Uint256 is a type that represents an 256-bit unsigned integer.
type Uint256 [4]uint64

// Add returns the sum a+b.
//
// This function's execution time does not depend on the inputs.
func (a Uint256) Add(b Uint256) Uint256 {
	u3, carry := bits.Add64(a[3], b[3], 0)
	u2, carry := bits.Add64(a[2], b[2], carry)
	u1, carry := bits.Add64(a[1], b[1], carry)
	u0, _ := bits.Add64(a[0], b[0], carry)
	return Uint256{u0, u1, u2, u3}
}

// Sub returns the difference a-b.
//
// This function's execution time does not depend on the inputs.
func (a Uint256) Sub(b Uint256) Uint256 {
	u3, borrow := bits.Sub64(a[3], b[3], 0)
	u2, borrow := bits.Sub64(a[2], b[2], borrow)
	u1, borrow := bits.Sub64(a[1], b[1], borrow)
	u0, _ := bits.Sub64(a[0], b[0], borrow)
	return Uint256{u0, u1, u2, u3}
}

// Text returns the string representation of a in the given base.
// Base must be between 2 and 62, inclusive.
// The result uses the lower-case letters 'a' to 'z' for digit values 10 to 35,
// and the upper-case letters 'A' to 'Z' for digit values 36 to 61. No prefix (such as "0x") is added to the string.
func (a Uint256) Text(base int) string {
	_, s := formatBits256(nil, a[0], a[1], a[2], a[3], base, false, false)
	return s
}

// Append appends the string representation of a, as generated by a.Text(base), to buf and returns the extended buffer.
func (a Uint256) Append(dst []byte, base int) []byte {
	d, _ := formatBits256(dst, a[0], a[1], a[2], a[3], base, false, true)
	return d
}

// AppendText implements the [encoding.TextAppender] interface.
func (a Uint256) AppendText(dst []byte) ([]byte, error) {
	d, _ := formatBits256(dst, a[0], a[1], a[2], a[3], 10, false, true)
	return d, nil
}

// String returns the string representation of a in base 10.
func (a Uint256) String() string {
	_, s := formatBits256(nil, a[0], a[1], a[2], a[3], 10, false, false)
	return s
}
