package ints

import "math/bits"

// Uint1024 is a type that represents an 1024-bit unsigned integer.
type Uint1024 [16]uint64

// Add returns the sum a+b.
//
// This function's execution time does not depend on the inputs.
func (a Uint1024) Add(b Uint1024) Uint1024 {
	u15, carry := bits.Add64(a[15], b[15], 0)
	u14, carry := bits.Add64(a[14], b[14], carry)
	u13, carry := bits.Add64(a[13], b[13], carry)
	u12, carry := bits.Add64(a[12], b[12], carry)
	u11, carry := bits.Add64(a[11], b[11], carry)
	u10, carry := bits.Add64(a[10], b[10], carry)
	u9, carry := bits.Add64(a[9], b[9], carry)
	u8, carry := bits.Add64(a[8], b[8], carry)
	u7, carry := bits.Add64(a[7], b[7], carry)
	u6, carry := bits.Add64(a[6], b[6], carry)
	u5, carry := bits.Add64(a[5], b[5], carry)
	u4, carry := bits.Add64(a[4], b[4], carry)
	u3, carry := bits.Add64(a[3], b[3], carry)
	u2, carry := bits.Add64(a[2], b[2], carry)
	u1, carry := bits.Add64(a[1], b[1], carry)
	u0, _ := bits.Add64(a[0], b[0], carry)
	return Uint1024{u0, u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14, u15}
}

// Sub returns the difference a-b.
//
// This function's execution time does not depend on the inputs.
func (a Uint1024) Sub(b Uint1024) Uint1024 {
	u15, borrow := bits.Sub64(a[15], b[15], 0)
	u14, borrow := bits.Sub64(a[14], b[14], borrow)
	u13, borrow := bits.Sub64(a[13], b[13], borrow)
	u12, borrow := bits.Sub64(a[12], b[12], borrow)
	u11, borrow := bits.Sub64(a[11], b[11], borrow)
	u10, borrow := bits.Sub64(a[10], b[10], borrow)
	u9, borrow := bits.Sub64(a[9], b[9], borrow)
	u8, borrow := bits.Sub64(a[8], b[8], borrow)
	u7, borrow := bits.Sub64(a[7], b[7], borrow)
	u6, borrow := bits.Sub64(a[6], b[6], borrow)
	u5, borrow := bits.Sub64(a[5], b[5], borrow)
	u4, borrow := bits.Sub64(a[4], b[4], borrow)
	u3, borrow := bits.Sub64(a[3], b[3], borrow)
	u2, borrow := bits.Sub64(a[2], b[2], borrow)
	u1, borrow := bits.Sub64(a[1], b[1], borrow)
	u0, _ := bits.Sub64(a[0], b[0], borrow)
	return Uint1024{u0, u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14, u15}
}

// Sign returns the sign of a.
// It returns 1 if a > 0, and 0 if a == 0.
// It does not return -1 because Uint128 is unsigned.
func (a Uint1024) Sign() int {
	var zero Uint1024
	if a == zero {
		return 0
	}
	return 1
}

// Neg returns the negation of a.
//
// This function's execution time does not depend on the inputs.
func (a Uint1024) Neg() Uint1024 {
	u15, borrow := bits.Sub64(0, a[15], 0)
	u14, borrow := bits.Sub64(0, a[14], borrow)
	u13, borrow := bits.Sub64(0, a[13], borrow)
	u12, borrow := bits.Sub64(0, a[12], borrow)
	u11, borrow := bits.Sub64(0, a[11], borrow)
	u10, borrow := bits.Sub64(0, a[10], borrow)
	u9, borrow := bits.Sub64(0, a[9], borrow)
	u8, borrow := bits.Sub64(0, a[8], borrow)
	u7, borrow := bits.Sub64(0, a[7], borrow)
	u6, borrow := bits.Sub64(0, a[6], borrow)
	u5, borrow := bits.Sub64(0, a[5], borrow)
	u4, borrow := bits.Sub64(0, a[4], borrow)
	u3, borrow := bits.Sub64(0, a[3], borrow)
	u2, borrow := bits.Sub64(0, a[2], borrow)
	u1, borrow := bits.Sub64(0, a[1], borrow)
	u0, _ := bits.Sub64(0, a[0], borrow)
	return Uint1024{u0, u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14, u15}
}

// Text returns the string representation of a in the given base.
// Base must be between 2 and 62, inclusive.
// The result uses the lower-case letters 'a' to 'z' for digit values 10 to 35,
// and the upper-case letters 'A' to 'Z' for digit values 36 to 61. No prefix (such as "0x") is added to the string.
func (a Uint1024) Text(base int) string {
	_, s := formatBits1024(nil, a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7], a[8], a[9], a[10], a[11], a[12], a[13], a[14], a[15], base, false, false)
	return s
}

// Append appends the string representation of a, as generated by a.Text(base), to buf and returns the extended buffer.
func (a Uint1024) Append(dst []byte, base int) []byte {
	d, _ := formatBits1024(dst, a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7], a[8], a[9], a[10], a[11], a[12], a[13], a[14], a[15], base, false, true)
	return d
}

// AppendText implements the [encoding.TextAppender] interface.
func (a Uint1024) AppendText(dst []byte) ([]byte, error) {
	d, _ := formatBits1024(dst, a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7], a[8], a[9], a[10], a[11], a[12], a[13], a[14], a[15], 10, false, true)
	return d, nil
}

// String returns the string representation of a in base 10.
func (a Uint1024) String() string {
	_, s := formatBits1024(nil, a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7], a[8], a[9], a[10], a[11], a[12], a[13], a[14], a[15], 10, false, false)
	return s
}
